version: "2"
services:
  kube-apiserver:
    image: gcr.io/google_containers/hyperkube:v1.12.0
    network_mode: host
    entrypoint: ["kube-apiserver",
      "--advertise-address=10.20.165.26",
      "--allow-privileged=true",
      "--apiserver-count=3",
      "--audit-log-maxage=30", 
      "--audit-log-maxbackup=3", 
      "--audit-log-maxsize=100",
      "--audit-log-path=/var/log/audit.log",
      "--authorization-mode=Node,RBAC",
      "--bind-address=0.0.0.0",
      "--client-ca-file=/var/lib/kubernetes/ca.pem",
      "--enable-admission-plugins=Initializers,NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota",
      "--enable-swagger-ui=true",
      "--etcd-cafile=/var/lib/kubernetes/ca.pem",
      "--etcd-certfile=/var/lib/kubernetes/kubernetes.pem",
      "--etcd-keyfile=/var/lib/kubernetes/kubernetes-key.pem",
      "--etcd-servers=https://10.20.165.26:2379",
      "--event-ttl=1h",
      "--experimental-encryption-provider-config=/var/lib/kubernetes/encryption-config.yaml",
      "--kubelet-certificate-authority=/var/lib/kubernetes/ca.pem",
      "--kubelet-client-certificate=/var/lib/kubernetes/kubernetes.pem",
      "--kubelet-client-key=/var/lib/kubernetes/kubernetes-key.pem",
      "--kubelet-https=true",
      "--runtime-config=api/all",
      "--service-account-key-file=/var/lib/kubernetes/service-account.pem",
      "--service-cluster-ip-range=10.32.0.0/24",
      "--service-node-port-range=30000-32767",
      "--tls-cert-file=/var/lib/kubernetes/kubernetes.pem",
      "--tls-private-key-file=/var/lib/kubernetes/kubernetes-key.pem",
      "--v=2"]
    ports:
       - 6443:6443
    volumes:
      - /var/lib/kubernetes/ca.pem:/var/lib/kubernetes/ca.pem
      - /var/lib/kubernetes/kubernetes.pem:/var/lib/kubernetes/kubernetes.pem
      - /var/lib/kubernetes/kubernetes-key.pem:/var/lib/kubernetes/kubernetes-key.pem
      - /var/lib/kubernetes/encryption-config.yaml:/var/lib/kubernetes/encryption-config.yaml
      - /var/lib/kubernetes/service-account.pem:/var/lib/kubernetes/service-account.pem
  kube-controller-manager:
    image: gcr.io/google_containers/hyperkube:v1.12.0
    network_mode: host
    entrypoint: [ "kube-controller-manager",
      "--address=0.0.0.0",
      "--cluster-cidr=10.200.0.0/16",
      "--cluster-name=kubernetes",
      "--cluster-signing-cert-file=/var/lib/kubernetes/ca.pem",
      "--cluster-signing-key-file=/var/lib/kubernetes/ca-key.pem",
      "--kubeconfig=/var/lib/kubernetes/kube-controller-manager.kubeconfig",
      "--leader-elect=true",
      "--root-ca-file=/var/lib/kubernetes/ca.pem",
      "--service-account-private-key-file=/var/lib/kubernetes/service-account-key.pem",
      "--service-cluster-ip-range=10.32.0.0/24",
      "--use-service-account-credentials=true",
      "--v=2"]
    volumes:
      - /var/lib/kubernetes/ca.pem:/var/lib/kubernetes/ca.pem
      - /var/lib/kubernetes/ca-key.pem:/var/lib/kubernetes/ca-key.pem
      - /var/lib/kubernetes/kube-controller-manager.kubeconfig:/var/lib/kubernetes/kube-controller-manager.kubeconfig
      - /var/lib/kubernetes/service-account-key.pem:/var/lib/kubernetes/service-account-key.pem
  kube-scheduler:
    image: gcr.io/google_containers/hyperkube:v1.12.0
    network_mode: host
    entrypoint: ["kube-scheduler", "--config=/etc/kubernetes/config/kube-scheduler.yaml", "--v=2"]
    volumes:
     - /etc/kubernetes/config/kube-scheduler.yaml:/etc/kubernetes/config/kube-scheduler.yaml
     - /var/lib/kubernetes/kube-scheduler.kubeconfig:/var/lib/kubernetes/kube-scheduler.kubeconfig